# Generated by Django 3.2.13 on 2022-05-11 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('deletedAt', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
            ],
        ),
        migrations.CreateModel(
            name='Atom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255, verbose_name='Term')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('deletedAt', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
            ],
        ),
        migrations.CreateModel(
            name='Axiom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField(default=True)),
                ('sentence', models.CharField(max_length=255, verbose_name='Sentence')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('deletedAt', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
            ],
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid', models.BooleanField(default=True)),
                ('sentence', models.CharField(max_length=255, verbose_name='Sentence')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('deletedAt', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
            ],
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('deletedAt', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('action_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.action')),
                ('knowledge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.knowledge')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='atom_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.atom'),
        ),
        migrations.AddField(
            model_name='action',
            name='axiom_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.axiom'),
        ),
    ]
