# Generated by Django 3.2.13 on 2022-05-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.JSONField(verbose_name='Tags')),
                ('information', models.CharField(blank=True, max_length=255, null=True, verbose_name='Information')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('deletedAt', models.DateTimeField(verbose_name='Deleted at')),
            ],
        ),
    ]
