# Generated by Django 3.2.13 on 2022-05-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_rename_contact_businessrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessrule',
            name='deletedAt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
    ]
